{{- if and .Values.prometheus.enabled .Values.prometheus.prometheusIngress.enabled (eq .Values.prometheus.prometheusIngress.ingressClassName "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-prometheus-strip-prefix
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-prometheus-strip-prefix
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  stripPrefix:
    prefixes:
      - /prometheus
{{- end }}
