{{- /*
Copyright 2025 SUSE LLC
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if and .Values.prometheus.enabled .Values.prometheus.prometheusIngress.auth.enabled }}
{{- $username := required "prometheus.prometheusIngress.auth.username is required when auth is enabled" .Values.prometheus.prometheusIngress.auth.username }}
{{- $password := required "prometheus.prometheusIngress.auth.password is required when auth is enabled" .Values.prometheus.prometheusIngress.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  labels:
    app.kubernetes.io/name: prometheus-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  users: {{ htpasswd $username $password | b64enc | quote }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-basic-auth
  labels:
    app.kubernetes.io/name: prometheus-basic-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  basicAuth:
    secret: prometheus-basic-auth
{{- end }}
