{{- /*
Copyright 2025 SUSE LLC
SPDX-License-Identifier: Apache-2.0
*/}}
{{ if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "trento-web.fullname" . }}-no-introspection
  labels:
  {{- include "trento-web.labels" . | nindent 4 }}
spec:
  replacePathRegex:
    regex: "^/api/session/token/introspect$"
    replacement: "/not-found"
{{- end }}
